- name: Check nvm installed in Local
  tags: nvm
  shell: test -d ~/.nvm ; echo $?
  register: nvm_installed
  ignore_errors: true

- name: Install nvm in Local
  when: nvm_installed.stdout == '1'
  tags: nvm
  git:
    repo: "{{ nvm_repo_url }}"
    dest: ~/.nvm

- name: Add nvm path in CentOS
  when: ansible_distribution == "CentOS"
  tags: nvm
  lineinfile:
    dest: "~/.bash_profile"
    line: "{{ item }}"
  with_items:
    - '# nvm'
    - export NVM_DIR=$HOME/.nvm
    - source $NVM_DIR/nvm.sh

- name: Add nvm path in Ubuntu
  when: ansible_distribution == "Ubuntu"
  tags: nvm
  lineinfile:
    dest: "~/.profile"
    line: "{{ item }}"
  with_items:
    - '# nvm'
    - export NVM_DIR=$HOME/.nvm
    - source $NVM_DIR/nvm.sh

- name: Check node.js installed in Local
  tags: nvm
  shell: bash -lc "nvm ls | grep {{ node_version }}"
  register: node_installed
  ignore_errors: true

- name: Install node.js in Local
  when: node_installed.rc == 1
  tags: nvm
  shell: bash -lc "nvm install {{ node_version }}"

- name: Install node npm packages in Local
  tags: nvm
  shell: bash -lc "nvm use {{ node_version }} && npm install -g {{ item }}"
  with_items: npm_packages

- name: Modify nvm alias in Local
  tags: nvm
  shell: bash -lc "nvm use {{ default_version }} && nvm alias default {{ default_version }}"
