- name: Install nginx repo
  sudo: true
  tags: nginx
  yum: name={{ nginx_repo_url }} state=present

- name: Install nginx
  sudo: true
  tags: nginx
  yum: name=nginx state=latest

- name: Put conf
  sudo: true
  tags: nginx
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/conf.d/{{ item }}"
  with_items:
    - local.conf

- name: Turn nginx service on
  sudo: true
  tags: nginx
  service: name=nginx enabled=yes state=restarted
