- name: Check nvm installed
  tags: nvm
  shell: test -d ~/.nvm ; echo $?
  register: nvm_installed
  ignore_errors: true

- name: Install nvm
  tags: nvm
  git:
    repo: "{{ nvm_repo_url }}"
    dest: ~/.nvm
  when: nvm_installed.stdout == '1'

- name: Check node.js installed
  tags: nvm
  shell: source ~/.nvm/nvm.sh && nvm ls | grep {{ node_version }} ; echo $?
  register: node_installed

- name: Install node.js
  tags: nvm
  shell: source ~/.nvm/nvm.sh && nvm install {{ node_version }}
  when: node_installed.stdout == '1'

- name: Install node npm packages
  tags: nvm
  npm:
    executable: "~/.nvm/versions/node/{{ node_version }}/bin/npm"
    state: present
    name: "{{ item }}"
    global: yes
  with_items: npm_packages

- name: Check iojs installed
  tags: nvm
  shell: source ~/.nvm/nvm.sh && nvm ls | grep {{ iojs_version }} ; echo $?
  register: iojs_installed

- name: Install io.js
  tags: nvm
  shell: source ~/.nvm/nvm.sh && nvm install {{ iojs_version }}
  when: iojs_installed.stdout == '1'

- name: Install iojs npm packages
  tags: nvm
  npm:
    executable: "~/.nvm/versions/io.js/{{ iojs_version|replace('iojs-', '') }}/bin/npm"
    state: present
    name: "{{ item }}"
    global: yes
  with_items: npm_packages

- name: Modify nvm alias
  tags: nvm
  shell: source ~/.nvm/nvm.sh && nvm use {{ default_version }} && nvm alias default {{ default_version }}

- name: Add init nvm
  tags: nvm
  lineinfile:
    dest: ~/.bash_profile
    line: source ~/.nvm/nvm.sh
