#- name: Install remi
#  sudo: true
#  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present
#
#- name: Install Maria
#  sudo: true
#  yum: name={{ item }} state=present enablerepo=remi
#  with_items:
#    - mariadb
#    - mariadb-server
#    - mariadb-devel
#
#- name: Turn MariaDB service on
#  sudo: yes
#  service:
#    name: mariadb
#    state: started
#    enabled: yes
- name: Remove MariaDB
  sudo: true
  tags: mysql
  yum: name={{ item }} state=absent
  with_items: mariadb_packages

- name: Install MySQL repo
  sudo: true
  tags: mysql
  yum: name={{ mysql_repo_url }} state=present

- name: Install MySQL
  sudo: true
  tags: mysql
  yum: name={{ item }} state=latest
  with_items: mysql_packages

- name: Turn mysql service on
  sudo: true
  tags: mysql
  service: name=mysql state=restarted enabled=yes
