- name: Download jenkins repo in CentOS
  when: ansible_distribution == "CentOS"
  tags: jenkins
  sudo: true
  get_url: url={{ jenkins_repo_url }} dest=/etc/yum.repos.d/jenkins.repo

- name: Add apt-key
  when: ansible_distribution == "Ubuntu"
  tags: jenkins
  sudo: true
  apt_key: url={{ jenkins_apt_key_url }} state=present

- name: Add jenkins repo
  when: ansible_distribution == "Ubuntu"
  tags: jenkins
  sudo: true
  shell: "sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'"

- name: Install jenkins rpm key in CentOS
  when: ansible_distribution == "CentOS"
  tags: jenkins
  sudo: true
  rpm_key: key={{ jenkins_rpm_key_url }} state=present

- name: Install jenkins via yum
  when: ansible_distribution == "CentOS"
  tags: jenkins
  sudo: true
  yum: name=jenkins state=latest

- name: Install jenkins via apt
  when: ansible_distribution == "Ubuntu"
  tags: jenkins
  sudo: true
  apt: name=jenkins state=latest update_cache=yes

- name: Change JENKINS_PORT in CentOS
  when: ansible_distribution == "CentOS"
  tags: jenkins
  sudo: true
  replace:
    dest: /etc/sysconfig/jenkins
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - regexp: '^JENKINS_PORT="8080"$'
      replace: 'JENKINS_PORT="{{ jenkins_port }}"'
    - regexp: '^JENKINS_AJP_PORT="8009"$'
      replace: 'JENKINS_AJP_PORT=-1'

- name: Change HTTP_PORT in Ubuntu
  when: ansible_distribution == "Ubuntu"
  tags: jenkins
  sudo: true
  replace:
    dest: /etc/default/jenkins
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - regexp: '^HTTP_PORT=8080$'
      replace: 'HTTP_PORT={{ jenkins_port }}'

- name: Restart Jenkins
  tags: jenkins
  sudo: true
  service: name=jenkins state=restarted enabled=yes

- name: Sleep for Jenkins restarted
  tags: jenkins
  pause: seconds=30

- name: Download jenkins-cli
  tags: jenkins
  sudo_user: jenkins
  get_url: url={{ jenkins_cli_download_url }} dest={{ jenkins_cli_path }}

- name: Install Jenkins Plugins
  tags: jenkins
  with_items: jenkins_plugins
  shell: java -jar {{ jenkins_cli_path }} -s {{ jenkins_url }} install-plugin {{ item }}

- name: Restart Jenkins
  tags: jenkins
  shell: java -jar {{ jenkins_cli_path }} -s {{ jenkins_url }} safe-restart
