- name: Install Redis Repo
  tags: redis
  become: true
  yum: name={{ redis_repo_url }} state=present

- name: Install Redis
  tags: redis
  become: true
  yum: name=redis state=latest

- name: Turn redis service on
  tags: redis
  become: true
  service: name=redis state=restarted enabled=yes
