- name: Install epel 7 repo
  when: ansible_distribution_major_version|int == 7 and ansible_distribution == "CentOS"
  sudo: true
  tags: yum
  yum: name={{ epel_repo_url }} state=present

- name: Install epel 6 repo
  when: ansible_distribution_major_version|int == 6 and ansible_distribution == "CentOS"
  sudo: true
  tags: yum
  yum: name={{ epel_repo_url }} state=present

- name: Update yum
  when: ansible_distribution == "CentOS"
  sudo: true
  tags: yum
  yum: name=* state=latest

- name: Update apt
  when: ansible_distribution == "Ubuntu"
  sudo: true
  tags: apt
  apt: upgrade=dist update_cache=yes

- name: Install essential yum packages
  when: ansible_distribution == "CentOS"
  sudo: true
  tags: yum
  yum: name={{ item }} state=latest
  with_items: yum_packages

- name: Install essential apt packages
  when: ansible_distribution == "Ubuntu"
  sudo: true
  tags: apt
  apt: name={{ item }} state=latest update_cache=yes
  with_items: apt_packages

- name: Install nkf via yum
  when: ansible_distribution == "CentOS"
  sudo: true
  tags: yum
  yum: name={{ nkf_repo_url }} state=present

- name: Install ag via yum
  when: ansible_distribution_major_version|int == 7 and ansible_distribution == "CentOS"
  sudo: true
  tags: yum
  yum: name=the_silver_searcher state=latest

- name: Install ag via yum adding RPM
  when: ansible_distribution_major_version|int == 6 and ansible_distribution == "CentOS"
  sudo: true
  tags: yum
  yum: name={{ ag_repo_url }} state=present

- name: Create ssh key
  tags: ssh
  user: name=vagrant state=present generate_ssh_key=yes

- name: Add alias
  when: ansible_distribution == "CentOS"
  tags: rc
  lineinfile:
    dest: "~/{{centos_bash_profile}}"
    line: "{{ item }}"
  with_items:
    - '# Alias'
    - alias vi='vim'
    - alias view='vim -R'
    - alias be='bundle exec'

- name: Add alias
  when: ansible_distribution == "Ubuntu"
  tags: rc
  lineinfile:
    dest: "~/{{ubuntu_bash_profile}}"
    line: "{{ item }}"
  with_items:
    - '# Alias'
    - alias vi='vim'
    - alias view='vim -R'
    - alias be='bundle exec'

- name: Download git-completion and git-prompt
  tags: rc
  sudo: true
  get_url: url={{ item }} dest=/etc/bash_completion.d/
  with_items: git_contrib_repo_urls

- name: Remove old git completion
  tags: rc
  sudo: true
  file: name=/etc/bash_completion.d/git state=absent

- name: Add prompt
  when: ansible_distribution == "CentOS"
  tags: rc
  lineinfile:
    dest: "~/{{centos_bash_profile}}"
    line: "{{item}}"
  with_items:
    - '# git'
    - PS1='[\u:\W$(__git_ps1 "(%s)")]$ '

- name: Add prompt
  when: ansible_distribution == "Ubuntu"
  tags: rc
  lineinfile:
    dest: "~/{{ubuntu_bash_profile}}"
    line: "{{item}}"
  with_items:
    - '# git'
    - PS1='[\u:\W$(__git_ps1 "(%s)")]$ '

- name: Turn selinux off
  when: ansible_distribution == "CentOS"
  sudo: true
  tags: selinux
  selinux: state=disabled

- name: Install pip to system python
  when: ansible_distribution == "CentOS"
  tags: system_python
  shell: curl {{ pip_installer_url }} | sudo python

- name: Install pip packages for ansible
  when: ansible_distribution == "CentOS"
  tags: system_python
  sudo: true
  pip: name={{ item }} state=present
  with_items: pip_packages
